### ISSUE TITLE
issue2 - add global speed to map engine

### ISSUE THREAD

**Issue by klhead** [mmitss/mmitss-common#2]
Currently, the map engine expects speed to be defined per lane, but the standard (J2735 2016) specifies that lane level speed is optional and provides for a global speed. While we agree lane level is preferred, the USDOT MAP Tool (https://webapp.connectedvcs.com/isd/) only provides for the global speed value. A request has been sent to the USDOT team asking for the modification of the tool also.

**Comment by skeatonUA** [comment]
This fix has been implemented, tested, and merged into develop with https://github.com/mmitss/mmitss-common/commit/19e55862c344b32626d022ca1d4246e7e81c113b
